# Dependencies
markdown            : kramdown
highlighter         : Rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Permalinks
permalink           : pretty

# Setup
title               : Maymanko's Blog
tagline             : 'A Jekyll theme'
description         : 'Blog for life, dev and Vietnam'
url                 : /
baseurl             : ""

# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir          : _sass
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 10
future              : false
unpublished         : false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category         : '/category/:name/'

author:
  name              : 'Lee Won Hee'
  url               : https://twitter.com/

paginate            : 5

github:
  repo              : https://github.com/lwh4022