collections:
  develops:
    output: true
  lifes:
    output: true
  vietnams:
    output: true


title: Maymanko's blog
url: "https://lwh4022.github.io"
baseurl: ""
permalink: pretty

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
  
plugins:
- jekyll-sitemap
- jekyll-seo-tag