title: Maymanko's blog
url: "https://lwh4022.github.io"
baseurl: ""
permalink: pretty

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true


jekyll-archives:
  enabled: 
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/
  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives