# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maymanko's Blog
tagline:          'A Jekyll theme'
description:      'Blog for life, dev and Vietnam'
url:              /
baseurl:          /

author:
  name:           'Lee Won Hee'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lwh4022
